spring.application.name=baseEx

# habilita para que o console H2 veja o banco no browser
spring.h2.console.enabled=false
#true
spring.h2.console.path=/h2-console

# Conexão do banco de dados ( padrão para in-memory h2)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=  
#password

# especifica o dialeto H2 para o Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# opcional : mostrar SQL no console
spring.jpa.show-sql=false
#true
# para testar inicie o projeto
#   mvn spring-boot:run
# e va para o console no browser em
#   http://localhost:8080/h2-console


# Porta dinâmica (Render injeta via variável PORT)
server.port=${PORT:8080}



